# Generated by Django 5.0.6 on 2024-05-19 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('uuid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('admin', models.IntegerField(null=True)),
                ('account', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('dname', models.CharField(max_length=255)),
                ('dmajor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('rtime', models.IntegerField()),
                ('rname', models.CharField(max_length=255)),
                ('rbuilding', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('psgrade', models.IntegerField(null=True)),
                ('pcid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.courses')),
                ('pdid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.departments')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='crid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.rooms'),
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('suid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sgrade', models.IntegerField()),
                ('sdid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.departments')),
                ('suuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='scores',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('score', models.FloatField(null=True)),
                ('scid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.courses')),
                ('suid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.students')),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('tuid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tdid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.departments')),
                ('tuuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.accounts')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='ctuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.teachers'),
        ),
    ]
